#ifndef commands_h
#define commands_h

#define INPUT_COMMAND_a "97"
#define INPUT_COMMAND_b "98"
#define INPUT_COMMAND_c "99"
#define INPUT_COMMAND_d "100"
#define INPUT_COMMAND_e "101"
#define INPUT_COMMAND_f "102"
#define INPUT_COMMAND_g "103"
#define INPUT_COMMAND_h "104"
#define INPUT_COMMAND_i "105"
#define INPUT_COMMAND_j "106"
#define INPUT_COMMAND_k "107"
#define INPUT_COMMAND_l "108"
#define INPUT_COMMAND_m "109"
#define INPUT_COMMAND_n "110"
#define INPUT_COMMAND_o "111"
#define INPUT_COMMAND_p "112"
#define INPUT_COMMAND_q "113"
#define INPUT_COMMAND_r "114"
#define INPUT_COMMAND_s "115"
#define INPUT_COMMAND_t "116"
#define INPUT_COMMAND_u "117"
#define INPUT_COMMAND_v "118"
#define INPUT_COMMAND_w "119"
#define INPUT_COMMAND_x "120"
#define INPUT_COMMAND_y "121"
#define INPUT_COMMAND_z "122"

#endif